# Site settings
title: "Carte Noire"
email: wangpc625@gmail.com
description: "stay hungry,stay foolish"
baseurl: ""
url: "http://shadow625.github.io/"
title_description: "A blog that records the growth of a single dog"
title_image: "image/IMG_2916.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/shadow625
addthis_id: ""
post_limit: 10

# Social usernames/URLs
twitter_username: shadow
github_username:  jacobtomlinson
linkedin_link: https://shadow625.github.io
google_plus_link: https://shadow625.github.io
stackoverflow_link: https://shadow625.github.io

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
