# Site settings
title: "shadow"
email: wangpc625@gmail.com
description: "stay hungry,stay foolish"
baseurl: ""
url: "http://shadow625.github.io/"
title_description: "A blog that records the growth of a single dog"
title_image: "image/IMG_2916.jpg"
google_analytics: "UA-20365477-4"
disqus_account: shadowgrand
github_repository: https://github.com/shadow625
addthis_id: ""
post_limit: 10

# Social usernames/URLs
twitter_username:  ""
github_username:  shadow625
linkedin_link: https://shadow625.github.io
google_plus_link: https://plus.google.com/u/0/115616945666848752661
stackoverflow_link: http://stackoverflow.com/users/5461353/shadow

# Footer
footer_left: "Made by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
